# Generated by Django 4.1.3 on 2024-03-18 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pathchecker_delete_blogpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pathchecker',
            old_name='content',
            new_name='path',
        ),
    ]
